# 05/10/2023

## Take1

In [1]:
import os
import tensorflow as tf

# Set the directory to save the model and data
directory = "/Users/d/Dropbox (Personal)/0g.κοσμογονία,γ/2.pantheon"

# Create train, val, test folders if they don't exist
train_dir = os.path.join(directory, "train")
val_dir = os.path.join(directory, "val")
test_dir = os.path.join(directory, "test")
for folder in [train_dir, val_dir, test_dir]:
    if not os.path.exists(folder):
        os.makedirs(folder)

# Set up the data generators for training and validation
train_data = tf.keras.preprocessing.image.ImageDataGenerator()
train_generator = train_data.flow_from_directory(train_dir, target_size=(224, 224), batch_size=32, class_mode="binary")
val_data = tf.keras.preprocessing.image.ImageDataGenerator()
val_generator = val_data.flow_from_directory(val_dir, target_size=(224, 224), batch_size=32, class_mode="binary")

# Set up the model
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16, (3,3), activation="relu", input_shape=(224,224,3)),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(1, activation="sigmoid")
])
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
model.fit(train_generator, epochs=10, validation_data=val_generator)

# Save the model
model.save(os.path.join(directory, "model.h5"))


2023-05-10 17:28:32.960374: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


Found 632 images belonging to 2 classes.


Found 0 images belonging to 0 classes.


Epoch 1/10


2023-05-10 17:28:37.232765: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]


 1/20 [>.............................] - ETA: 45s - loss: 87.1491 - accuracy: 0.0938

 2/20 [==>...........................] - ETA: 37s - loss: 112.9971 - accuracy: 0.5312

 3/20 [===>..........................] - ETA: 34s - loss: 329.8365 - accuracy: 0.6458

 4/20 [=====>........................] - ETA: 32s - loss: 323.2376 - accuracy: 0.7266

 5/20 [======>.......................] - ETA: 29s - loss: 359.7760 - accuracy: 0.7688

 6/20 [========>.....................] - ETA: 27s - loss: 461.1711 - accuracy: 0.7865

 7/20 [=========>....................] - ETA: 26s - loss: 534.6555 - accuracy: 0.8036

 8/20 [===========>..................] - ETA: 24s - loss: 565.4740 - accuracy: 0.8164

 9/20 [============>.................] - ETA: 22s - loss: 604.0518 - accuracy: 0.8229

10/20 [==============>...............] - ETA: 20s - loss: 591.1743 - accuracy: 0.8344

11/20 [===============>..............] - ETA: 18s - loss: 552.4883 - accuracy: 0.8466

12/20 [=================>............] - ETA: 15s - loss: 529.2424 - accuracy: 0.8537

## Take2

In [1]:
import os
import tensorflow as tf

# Set the directory to save the model and data
directory = "/Users/d/Dropbox (Personal)/0g.κοσμογονία,γ/2.pantheon"

# Create train, val, test folders if they don't exist
train_dir = os.path.join(directory, "train")
val_dir = os.path.join(directory, "val")
test_dir = os.path.join(directory, "test")
for folder in [train_dir, val_dir, test_dir]:
    if not os.path.exists(folder):
        os.makedirs(folder)

# Set up the data generators for training and validation
train_data = tf.keras.preprocessing.image.ImageDataGenerator()
train_generator = train_data.flow_from_directory(os.path.join(train_dir), target_size=(224, 224), batch_size=32, class_mode="binary", classes=['no', 'yes'])
val_data = tf.keras.preprocessing.image.ImageDataGenerator()
val_generator = val_data.flow_from_directory(val_dir, target_size=(224, 224), batch_size=32, class_mode="binary")

# Set up the model
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16, (3,3), activation="relu", input_shape=(224,224,3)),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(1, activation="sigmoid")
])
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
model.fit(train_generator, epochs=10, validation_data=val_generator)

# Save the model
model.save(os.path.join(directory, "model.h5"))


2023-05-10 15:16:19.115451: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


Found 632 images belonging to 2 classes.
Found 0 images belonging to 0 classes.
Epoch 1/10


2023-05-10 15:16:38.354653: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]


20/20 [==============================] - 42s 2s/step - loss: 786.2231 - accuracy: 0.8623
Epoch 2/10
20/20 [==============================] - 42s 2s/step - loss: 59.3953 - accuracy: 0.8513
Epoch 3/10
20/20 [==============================] - 41s 2s/step - loss: 15.4495 - accuracy: 0.9035
Epoch 4/10
20/20 [==============================] - 42s 2s/step - loss: 4.7708 - accuracy: 0.9415
Epoch 5/10
20/20 [==============================] - 44s 2s/step - loss: 0.7124 - accuracy: 0.9684
Epoch 6/10
20/20 [==============================] - 43s 2s/step - loss: 0.3184 - accuracy: 0.9842
Epoch 7/10
20/20 [==============================] - 42s 2s/step - loss: 0.0626 - accuracy: 0.9937
Epoch 8/10
20/20 [==============================] - 42s 2s/step - loss: 0.0165 - accuracy: 0.9984
Epoch 9/10
20/20 [==============================] - 43s 2s/step - loss: 7.2328e-04 - accuracy: 1.0000
Epoch 10/10
20/20 [==============================] - 43s 2s/step - loss: 6.9006e-07 - accuracy: 1.0000


```stata
7m 30.3s

2023-05-10 15:16:19.115451: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Found 632 images belonging to 2 classes.
Found 0 images belonging to 0 classes.
Epoch 1/10
2023-05-10 15:16:38.354653: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]
20/20 [==============================] - 42s 2s/step - loss: 786.2231 - accuracy: 0.8623
Epoch 2/10
20/20 [==============================] - 42s 2s/step - loss: 59.3953 - accuracy: 0.8513
Epoch 3/10
20/20 [==============================] - 41s 2s/step - loss: 15.4495 - accuracy: 0.9035
Epoch 4/10
20/20 [==============================] - 42s 2s/step - loss: 4.7708 - accuracy: 0.9415
Epoch 5/10
20/20 [==============================] - 44s 2s/step - loss: 0.7124 - accuracy: 0.9684
Epoch 6/10
20/20 [==============================] - 43s 2s/step - loss: 0.3184 - accuracy: 0.9842
Epoch 7/10
20/20 [==============================] - 42s 2s/step - loss: 0.0626 - accuracy: 0.9937
Epoch 8/10
20/20 [==============================] - 42s 2s/step - loss: 0.0165 - accuracy: 0.9984
Epoch 9/10
20/20 [==============================] - 43s 2s/step - loss: 7.2328e-04 - accuracy: 1.0000
Epoch 10/10
20/20 [==============================] - 43s 2s/step - loss: 6.9006e-07 - accuracy: 1.0000

```